{% set name = "kotsu" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kotsu-{{ version }}.tar.gz
  sha256: b344cb3ad0a6ba1f1ffea90ba2d53749273a9851b1651f3dfbb1b25b33f464ac

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pandas
    - typing-extensions

test:
  imports:
    - kotsu
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/datavaluepeople/kotsu
  summary: Lightweight framework for structured and repeatable model validation
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - DBCerigo
    - ali-tny
    - alex-hh
