{% set name = "kotsu" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/kotsu-{{ version }}.tar.gz
  sha256: 686b2f1441e6e026638b1e4050e045d5fed5daa741de797e086182c36eb67e69

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pandas
    - typing-extensions

test:
  imports:
    - kotsu
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/datavaluepeople/kotsu
  summary: Lightweight framework for structured and repeatable model validation
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - DBCerigo
    - ali-tny
    - alex-hh
